/**
 * Hand-built Merkle Patricia Trie fixtures for StateProver tests.
 *
 * No live RPC/trie library is available in this repo, so these fixtures are
 * constructed directly from trusted, independent primitives — viem's own
 * `toRlp`/`keccak256` plus a hex-prefix encoder written fresh here (the
 * inverse of, but independent from, `decodeHexPrefix` under test) — rather
 * than generated by the StateProver code being tested. This keeps the
 * fixtures an honest, non-circular check of the trie-walk implementation.
 */
import { keccak256, toBytes, toHex, toRlp, type Hex } from 'viem'

export function encodeHexPrefixPath(nibbles: number[], isLeaf: boolean): Uint8Array {
  const isOdd = nibbles.length % 2 === 1
  const flag = (isLeaf ? 0b10 : 0b00) | (isOdd ? 0b01 : 0b00)
  const bytes: number[] = []
  let i = 0
  if (isOdd) {
    bytes.push((flag << 4) | nibbles[0])
    i = 1
  } else {
    bytes.push(flag << 4)
  }
  for (; i < nibbles.length; i += 2) {
    bytes.push((nibbles[i] << 4) | nibbles[i + 1])
  }
  return new Uint8Array(bytes)
}

/** Minimal big-endian bytes for a non-negative bigint (RLP integer convention: 0 -> empty). */
export function minimalBytes(value: bigint): Uint8Array {
  if (value === 0n) return new Uint8Array(0)
  let hex = value.toString(16)
  if (hex.length % 2 === 1) hex = `0${hex}`
  const bytes = new Uint8Array(hex.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

export function keyToNibblesLocal(key: Uint8Array): number[] {
  const nibbles: number[] = []
  for (const byte of key) nibbles.push(byte >> 4, byte & 0x0f)
  return nibbles
}

/** Empty branch children: 16 empty slots + empty value slot. */
function emptyBranchItems(): Uint8Array[] {
  return Array.from({ length: 17 }, () => new Uint8Array(0))
}

export interface AccountFields {
  nonce: bigint
  balance: bigint
  storageRoot: Hex
  codeHash: Hex
}

export function encodeAccountRlp(account: AccountFields): Uint8Array {
  return toRlp(
    [
      toHex(minimalBytes(account.nonce)),
      toHex(minimalBytes(account.balance)),
      account.storageRoot,
      account.codeHash,
    ],
    'bytes',
  )
}

/**
 * Builds a trivial single-leaf trie: the root node IS the leaf. Returns the
 * root hash and a 1-entry proof array. Valid for both account and storage
 * tries — pass the full 64-nibble key path and the raw (already RLP-encoded,
 * for storage: doubly so) leaf value bytes.
 */
export function buildSingleLeafTrie(nibbles: number[], leafValue: Uint8Array): { root: Hex; proof: Hex[] } {
  const path = encodeHexPrefixPath(nibbles, true)
  const leafNode = toRlp([toHex(path), toHex(leafValue)], 'bytes')
  return { root: keccak256(leafNode), proof: [toHex(leafNode)] }
}

/**
 * Builds a trie with one extension node (covering `nibbles.slice(0, branchDepth)`)
 * leading to one branch node, whose child at `nibbles[branchDepth]` is a
 * hash-referenced leaf holding `leafValue` for the remaining nibbles. A
 * second, unrelated branch slot is filled with an arbitrary 32-byte
 * placeholder hash so the branch node is well-formed — its content is never
 * dereferenced by the returned proof, exactly as in a real trie where
 * sibling subtrees are committed to by hash only.
 */
export function buildExtensionBranchTrie(
  nibbles: number[],
  branchDepth: number,
  leafValue: Uint8Array,
): { root: Hex; proof: Hex[] } {
  const targetNibble = nibbles[branchDepth]
  const siblingNibble = (targetNibble + 1) % 16

  const leafRemaining = nibbles.slice(branchDepth + 1)
  const leafPath = encodeHexPrefixPath(leafRemaining, true)
  const leafNode = toRlp([toHex(leafPath), toHex(leafValue)], 'bytes')
  const leafHash = toBytes(keccak256(leafNode))

  const siblingPlaceholder = keccak256(toBytes('sibling-placeholder'), 'bytes')

  const branchItems = emptyBranchItems()
  branchItems[targetNibble] = leafHash
  branchItems[siblingNibble] = siblingPlaceholder
  const branchNode = toRlp(branchItems, 'bytes')
  const branchHash = toBytes(keccak256(branchNode))

  const extPath = encodeHexPrefixPath(nibbles.slice(0, branchDepth), false)
  const extensionNode = toRlp([toHex(extPath), toHex(branchHash)], 'bytes')

  return {
    root: keccak256(extensionNode),
    proof: [toHex(extensionNode), toHex(branchNode), toHex(leafNode)],
  }
}

/**
 * Builds a trie identical in shape to {@link buildExtensionBranchTrie}, but
 * where the leaf under the target branch child is short enough (few
 * remaining nibbles, small value) that its RLP encoding is under 32 bytes —
 * forcing it to be embedded directly inside the branch node rather than
 * referenced by hash. The returned proof therefore has only 2 entries
 * (extension, branch); the embedded leaf is never a separate proof node.
 */
export function buildEmbeddedLeafTrie(
  nibbles: number[],
  branchDepth: number,
  leafValue: Uint8Array,
): { root: Hex; proof: Hex[] } {
  const targetNibble = nibbles[branchDepth]
  const siblingNibble = (targetNibble + 1) % 16

  const leafRemaining = nibbles.slice(branchDepth + 1)
  const leafPath = encodeHexPrefixPath(leafRemaining, true)
  const embeddedLeaf = [toHex(leafPath), toHex(leafValue)]

  // Sanity check for the fixture itself: confirm this really is embeddable.
  const encodedSize = toBytes(toRlp(embeddedLeaf, 'bytes' as never)).length
  if (encodedSize >= 32) {
    throw new Error(`fixture error: leaf is ${encodedSize} bytes, not embeddable (must be < 32)`)
  }

  const siblingPlaceholder = keccak256(toBytes('sibling-placeholder'), 'bytes')

  const branchItems: (Uint8Array | Hex[])[] = emptyBranchItems()
  branchItems[targetNibble] = embeddedLeaf
  branchItems[siblingNibble] = siblingPlaceholder
  const branchNode = toRlp(branchItems as never, 'bytes')
  const branchHash = toBytes(keccak256(branchNode))

  const extPath = encodeHexPrefixPath(nibbles.slice(0, branchDepth), false)
  const extensionNode = toRlp([toHex(extPath), toHex(branchHash)], 'bytes')

  return {
    root: keccak256(extensionNode),
    proof: [toHex(extensionNode), toHex(branchNode)],
  }
}
